### 1-d array

In [1]:
import numpy as np
# unlike a list, all values in a ndarray must be of the same type
# ndarray: n-dimensional array

a1 = np.arange(10)                          # array of 0 to 10, but not including 10
print('1-d array = \n', a1)

a2 = np.arange(0, 10, 2)                    # array of every 2nd unit in 0 to 10, but not including 10
print('\n1-d array with step = \n', a2)

1-d array = 
 [0 1 2 3 4 5 6 7 8 9]

1-d array with step = 
 [0 2 4 6 8]


### List to Array

In [2]:
list1 = [3, 1, 4, 1, 5]
b1 = np.array(list1)
print('1-d list to array = \n', b1)
print('dimensions = ', b1.shape)

list2 = [[2, 3, 4], [6, 5, 4], [8, 5, 2]]
b2 = np.array(list2)
print('\n3-d list to matrix = \n', b2)
print('dimensions = ', b2.shape)

list3 = [5, 1, 4, 1, 3]
b3 = np.array([list1, list3])
print('\ncombining lists into matrix = \n', b3)

b4 = np.array(list1 + list3)
print('\ncombining lists into 1-d array = \n', b4)

1-d list to array = 
 [3 1 4 1 5]
dimensions =  (5,)

3-d list to matrix = 
 [[2 3 4]
 [6 5 4]
 [8 5 2]]
dimensions =  (3, 3)

combining lists into matrix = 
 [[3 1 4 1 5]
 [5 1 4 1 3]]

combining lists into 1-d array = 
 [3 1 4 1 5 5 1 4 1 3]


### multi-dimensional matrices

In [3]:
m1 = np.zeros((2, 3))                       # 2x3 matrix of 0s
print('2x3 matrix of 0s = \n', m1)

m2 = np.ones((4, 4))                        # 4x4 matrix of 1s
print('\n4x4 matrix of 1s = \n', m2)

m3 = np.full((3, 2), 'N')                   # np.full for generating matrix of any value
print('\n 3x2 matrix of Ns = \n', m3)       # values can be of any type not just numbers

2x3 matrix of 0s = 
 [[0. 0. 0.]
 [0. 0. 0.]]

4x4 matrix of 1s = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 3x2 matrix of Ns = 
 [['N' 'N']
 ['N' 'N']
 ['N' 'N']]


### Identity and Random Matrices

In [4]:
p1 = np.eye(3)                              # identity matrices are always square, thus only 1 input
print('3x3 identity matrix = \n', p1)
print('dimensions of p1 = ', p1.shape)      # .shape attibute gives dimensions of a matrix/array

p2 = np.random.random()                     # single random value between 0 and 1
print('\nrandom number = \n', p2)

p3 = np.random.random(3)                    # array of 3 random values between 0 and 1
print('\nrandom array of length 3 = \n', p3)

p4 = np.random.random((2, 2))               # matrix of random numbers
print('\nrandom number matrix = \n', p4)    # random numbers from 0 to 1, non inclusive


3x3 identity matrix = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dimensions of p1 =  (3, 3)

random number = 
 0.6737667725180825

random array of length 3 = 
 [0.31291404 0.31616351 0.70442809]

random number matrix = 
 [[0.60308571 0.87005188]
 [0.62821558 0.76747043]]


### Array indexing

In [5]:
list3 = [[2.4, 3.2, 4.3], [6.5, 5.6, 4.6], [8.3, 5.2, 2.0]]
r1 = np.array(list3)

print('print entire array = \n', r1)                        # access entire matrix

print('\nprint 1st row = \n', r1[0])                        # access single row
print('\nprint 1st and last rows = \n', r1[[0, 1]])         # access list of rows

print('\nprint 2nd column = \n', r1[:, 1])                  # access single column

print('\nprint value at 0th row, 2nd col = \n', r1[0, 2])   # access index within a matrix

print entire array = 
 [[2.4 3.2 4.3]
 [6.5 5.6 4.6]
 [8.3 5.2 2. ]]

print 1st row = 
 [2.4 3.2 4.3]

print 1st and last rows = 
 [[2.4 3.2 4.3]
 [6.5 5.6 4.6]]

print 2nd column = 
 [3.2 5.6 5.2]

print value at 0th row, 2nd col = 
 4.3


### Reshaping Arrays

In [6]:
import numpy as np
# as long as the new shape can accomodate all elements and
# no new elements need to be added and it can create a proper matrix form
# any array or matrix can be reshaped into them

z = np.array([9,8,7,6,5,4])     # 1 row, 6 col
print('z = \n', z)

xz = z.reshape(3,-1)            # convert to 3 row, col determined automatically
print('\n3 row, auto-determined col = \n', xz)

yz = z.reshape(3,2)             # convert to 3 row, 2 col
print('\n3 row, 2 col = \n', yz)

z = 
 [9 8 7 6 5 4]

3 row, auto-determined col = 
 [[9 8]
 [7 6]
 [5 4]]

3 row, 2 col = 
 [[9 8]
 [7 6]
 [5 4]]
